steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

steps:
  - label: ":partyparrot:"
    command: "docker version; docker ps"
    plugins:
      - docker#v3.12.0:
          image: "bash:latest"
