steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
  - label: ":partyparrot:"
    command: 'echo "${BASH_VERSION}'
    plugins:
      - docker#v3.12.0:
          image: "bash:latest"
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.9.0:
          build: app
